// Package store defines the Store interface, the contract implemented by each
// engine. No other layer imports database/sql or drivers directly.
package store

import (
	"context"
	"fmt"
	"sync"

	"github.com/agmonetti/relm/internal/conn"
)

// Column describes a column of a table.
type Column struct {
	Name    string
	Type    string
	NotNull bool
	Default string
	PK      bool
}

// Result is the outcome of a query. Every cell is converted to a string in the
// store; the UI never makes type assertions.
type Result struct {
	Columns  []string
	Rows     [][]string
	Affected int64 // rows affected by an Exec; -1 when not applicable (read query)
	// Truncated is set when the scan stopped at a row limit before reaching
	// the end of the result set (see ScanResultMax).
	Truncated bool
}

// Index describes an index of a table.
type Index struct {
	Name    string
	Columns []string
	Unique  bool
}

// Store is the data access layer, neutral with respect to the engine.
type Store interface {
	// Connection
	Driver() string
	Version() (string, error)
	Close() error

	// Schema introspection
	Tables() ([]string, error)
	Columns(table string) ([]Column, error)
	Indexes(table string) ([]Index, error)

	// Arbitrary execution
	Query(sql string) (*Result, error)
	Exec(sql string) (int64, error)
	QueryContext(ctx context.Context, sql string) (*Result, error)
	ExecContext(ctx context.Context, sql string) (int64, error)
	// QueryContextMax runs a query that returns rows and stops after max rows
	// (0 = unlimited), marking Result.Truncated when the result is longer. Used
	// by the editor so a giant SELECT cannot exhaust the machine's memory.
	QueryContextMax(ctx context.Context, sql string, max int) (*Result, error)

	// Dialect: pagination and counting generated by the engine
	CountTable(table string) (int, error)
	SelectTablePage(table string, limit, offset int) (*Result, error)
	// SelectTableKeysetPage returns the page of rows strictly after the row
	// identified by cursor, ordered by the single-column key. cursor is the
	// key value of the last row of the previous page ("" for the first page).
	// It may return up to limit rows. Tables without a usable single-column
	// key use SelectTablePage instead.
	SelectTableKeysetPage(table, key string, limit int, cursor string) (*Result, error)
}

// Constructor is the function that creates a Store for an engine.
type Constructor func(conn.ConnectionConfig) (Store, error)

var (
	registryMu sync.RWMutex
	registry   = map[conn.Driver]Constructor{}
)

// Register registers an engine constructor. It is called from the init() of
// each engine package. It is compile-time configuration, not runtime state.
func Register(d conn.Driver, c Constructor) {
	registryMu.Lock()
	defer registryMu.Unlock()
	registry[d] = c
}

// New creates a Store according to the config. The engine must be registered.
func New(cfg conn.ConnectionConfig) (Store, error) {
	registryMu.RLock()
	c, ok := registry[cfg.Driver]
	registryMu.RUnlock()
	if !ok {
		return nil, fmt.Errorf("%w: %q", ErrUnsupportedDriver, cfg.Driver)
	}
	return c(cfg)
}
